mission2/Models/CalculatorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Linq;
using System.Threading.Tasks;

namespace mission2.Models
{
    public class CalculatorModel
    {
        [Required]
        [Range(0, 100)]
        public float assignments { get; set; }
        [Required]
        [Range(0, 100)]
        public float GroupProj { get; set; }
        [Required]
        [Range(0, 100)]
        public float quizes { get; set; }
        [Required]
        [Range(0, 100)]
        public float exams { get; set; }
        [Required]
        [Range(0, 100)]
        public float intex { get; set; }
    }
}

mission2/Controllers/BasicController.cs
using Microsoft.AspNetCore.Mvc;
using mission2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission2.Controllers
{
    public class BasicController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Calculator ()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Calculator (CalculatorModel model)
        {
            return View();
        }
    }
}

mission2/Views/Basic/Calculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Grade Calculator";
}
@model CalculatorModel
<!-- Grade Calculator -->
<p class="bold">Grade Calculator</p>
<p class="italic">Please Enter the grades (ex. 85.57 or 100) received in each category to calculate final grade.</p>
<form method="post">
    <label>Assignments</label>
    <input id="assignments" asp-for="assignments" /><br />
    <label>Group Project</label>
    <input id="GroupProj" asp-for="GroupProj" /><br />
    <label>Quizes</label>
    <input id="quizes" asp-for="quizes" /><br />
    <label>Exams</label>
    <input id="exams" asp-for="exams" /><br />
    <label>Intex</label>
    <input id="intex" asp-for="intex" /><br />
    <input type="submit" id="submit" class="btn1" value='Calculate' />
    <span id="output"></span>
    <div asp-validation-summary="All"></div>
</form>

mission2/Views/Basic/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Cole's Homepage";
}
    <!-- Header -->
    <h1>Cole Smith</h1><br /><br />
    <!-- Picture of Cole Playing Golf -->
    <img src="img/golf.jpg" alt="Cole playing golf with some friends" /><br /><br />
    <!-- Paragraph about IS 413 -->
    <p>
        I am very excited for IS413, Enterprise Application Development. Some of my favorite classes have been web development through javascript and python/django,
        so that gives me high hopes for this class as well. I hope to learn more about website development and add to my skillset through ASP.Net and C#.
    </p><br />

    <!-- Top 3 Careers -->
    <p class="bold">Here are the top 3 jobs I am interested in:</p>
    <ul>
        <li>Technology Consultant</li>
        <li>Developer</li>
        <li>Sports Data Analyst</li>
    </ul><br />

mission2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
    <meta charset="utf-8" />
    <link rel="icon" href="~/img/10-105431_png-file-svg-golf-icon-png-transparent-png.png" type="image/x-icon">
    <link href="~/css/default.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery-3.6.0.min.js"></script>
</head>
<body>
    <nav>
        <button><a asp-controller="Basic" asp-action="Index">Home</a></button>
        <button><a asp-controller="Basic" asp-action="Calculator">Grade Calculator</a></button>
    </nav>
    <div>
        @RenderBody()
    </div>

    <!-- JavaScript -->
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/calculator.js"></script>
</body>
</html>